/**
 * The offline pipeline on the mesh fixture: a synthetic configuration shaped
 * like a production routing mesh, generated by scripts/fixtures/generate-mesh.ts
 * and exported by Mirth 4.5.2 after every channel deployed
 * (scripts/fixtures/build-mesh.mjs).
 */
import { readdir, readFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { createExplodeEngine } from '../src/explode/index.js';
import { channelsOf, planPush } from '../src/push/index.js';
import { scanSecrets } from '../src/secrets/detect.js';
import { render, templatize } from '../src/secrets/index.js';
import type { CanonicalConfig, Json } from '../src/types.js';
import { XmlConfigAdapter } from '../src/xml/index.js';

type Obj = Record<string, Json>;
const FIXTURE = fileURLToPath(new URL('./fixtures/serverConfiguration.mesh.xml', import.meta.url));
const xml = new XmlConfigAdapter();
const engine = createExplodeEngine();

let text: string, config: CanonicalConfig, work: string, tree: string;
beforeAll(async () => {
  text = await readFile(FIXTURE, 'utf8');
  config = xml.parse(text);
  work = await mkdtemp(path.join(tmpdir(), 'channelvault-mesh-'));
  tree = path.join(work, 'tree');
  await engine.explode(config, { root: tree });
}, 60_000); // a 1 MB configuration, alongside the rest of the suite
afterAll(async () => {
  await rm(work, { recursive: true, force: true, maxRetries: 5, retryDelay: 50 });
});

const channel = (c: CanonicalConfig, name: string): Obj => channelsOf(c).find((ch) => ch['name'] === name)!;
/** The hub's i-th source transformer step. */
function hubStep(c: CanonicalConfig, i: number): Obj {
  const transformer = (channel(c, 'Order Hub')['sourceConnector'] as Obj)['transformer'] as Obj;
  return ((transformer['elements'] as Obj)['com.mirth.connect.plugins.javascriptstep.JavaScriptStep'] as Obj[])[i]!;
}

/** Every file under `dir`, relative, with its bytes. */
async function snapshot(dir: string): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  for (const e of await readdir(dir, { recursive: true, withFileTypes: true })) {
    if (e.isFile()) {
      const full = path.join(e.parentPath, e.name);
      out.set(path.relative(dir, full).split(path.sep).join('/'), await readFile(full, 'latin1'));
    }
  }
  return out;
}

describe('the mesh fixture', () => {
  it('is the shape it claims', () => {
    expect(config['@_version']).toBe('4.5.2');
    expect(channelsOf(config)).toHaveLength(26);
    const hub = channel(config, 'Order Hub');
    const dests = (hub['destinationConnectors'] as Obj)['connector'] as Obj[];
    expect(dests).toHaveLength(18);
    expect(new Set(dests.map((d) => d['transportName']))).toEqual(new Set(['Channel Writer', 'JavaScript Writer', 'SMTP Sender']));
    expect(dests.filter((d) => d['enabled'] === 'false')).toHaveLength(1);
  });

  it('round-trips through explode -> implode -> build', { timeout: 60_000 }, async () => {
    const imploded = await engine.implode({ root: tree });
    expect(imploded).toEqual(config);
    expect(xml.parse(xml.build(imploded))).toEqual(config);
  });

  it('writes the same files, byte for byte, every time it explodes', { timeout: 60_000 }, async () => {
    const again = path.join(work, 'again');
    await engine.explode(config, { root: again });
    expect(await snapshot(again)).toEqual(await snapshot(tree));
  });

  it('keeps every character of a script in its sidecar file', async () => {
    const script = hubStep(config, 1)['script'] as string;
    const file = await readFile(path.join(tree, 'channels', 'Order-Hub', 'source', 'transformer', '2.Tricky-text.js'), 'utf8');
    expect(file).toBe(script);
    for (const piece of [']]>', '\r\n', "';\rvar afterLoneCr", 'Größe · 日本語 · עברית · 😀', '{{not a placeholder}}', '${velocity.style}', '\tvar tabbed = true;   ']) {
      expect(file).toContain(piece);
    }
  });

  it('gives channels whose names collide their own directories', async () => {
    const dirs = await readdir(path.join(tree, 'channels'));
    expect(dirs).toHaveLength(26);
    // Which one gets the unsuffixed name follows the order the server lists them in.
    expect(dirs.filter((d) => /^lab-feed(-\d)?$/i.test(d))).toHaveLength(4);
    expect(new Set(dirs.map((d) => d.toLowerCase())).size).toBe(26);
  });

  // A restore changes the order Mirth lists channels in; a channel must not change directory.
  it('puts each channel in the same directory whatever order the server lists them in', { timeout: 60_000 }, async () => {
    const reversed = structuredClone(config);
    (reversed['channels'] as Obj)['channel'] = [...channelsOf(reversed)].reverse();
    const other = path.join(work, 'reversed');
    await engine.explode(reversed, { root: other });
    const dirOf = async (root: string) => {
      const out = new Map<string, string>();
      for (const d of await readdir(path.join(root, 'channels'))) {
        out.set(String((JSON.parse(await readFile(path.join(root, 'channels', d, 'channel.json'), 'utf8')) as Obj)['id']), d);
      }
      return out;
    };
    expect(await dirOf(other)).toEqual(await dirOf(tree));
  });

  it('names script files after steps, connectors and templates', async () => {
    const files = [...(await snapshot(tree)).keys()];
    expect(files).toContain('channels/Order-Hub/source/transformer/1.Route-by-type.js');
    expect(files).toContain('channels/Order-Hub/destinations/Archive-to-disk/writer.js');
    expect(files).toContain('channels/Results-MLLP/source/filter/2.Has-OBX.js');
    expect(files).toContain('codeTemplates/Shared-Core/library.json');
    expect(files).toContain('codeTemplates/JSON/jsonHelper1-2.js');
    const lookup = await readFile(path.join(tree, 'codeTemplates', 'Lookup', 'lookupCode.js'), 'utf8');
    expect(lookup.split('\n').length).toBeGreaterThan(10_000);
  });
});

describe('secrets in the mesh', () => {
  it('moves credentials and configuration-map values to the env file, and finds the one script password', () => {
    const templated = templatize(config, null, {});
    expect(Object.keys(templated.envUpdates)).toEqual(expect.arrayContaining([
      'ORDER_HUB__ALERT_ON_FAILURE__PASSWORD',
      'CONFIG_MAP__WORKLIST_PASSWORD',
      'CONFIG_MAP__ROUTES_JSON',
    ]));
    // Every other script (arrow functions, regex literals, template literals, E4X) is not a secret.
    const findings = scanSecrets(templated.config, { mode: 'find' }).findings;
    expect(findings.map((f) => `${f.kind} @ ${f.where}`)).toEqual(['db-connection-call @ Legacy Poller › sourceConnector › script']);

    const extracted = scanSecrets(templated.config, { mode: 'extract' });
    expect(JSON.stringify(extracted.config)).not.toContain('Fixture-Legacy-Pw1');
    expect(render(extracted.config, { ...templated.envUpdates, ...extracted.envUpdates })).toEqual(config);
  });
});

describe('planning a push against the mesh', () => {
  const edited = (edit: (c: CanonicalConfig) => void): CanonicalConfig => {
    const c = structuredClone(config);
    edit(c);
    return c;
  };

  it('finds nothing to push when nothing changed', () => {
    expect(planPush(config, config).changes).toEqual([]);
  });

  it('pushes only the channel whose step changed', () => {
    const local = edited((c) => { hubStep(c, 0)['script'] += '\n// edited'; });
    expect(planPush(local, config).changes.map((c) => `${c.op} ${c.label}`)).toEqual(['update Order Hub']);
  });

  // Mirth accepts both names; an update that keeps a name is not a clash.
  it('updates "Lab Feed" although "LAB FEED" exists', () => {
    const local = edited((c) => { channel(c, 'Lab Feed')['description'] = 'edited'; });
    expect(planPush(local, config).changes.map((c) => `${c.op} ${c.label}`)).toEqual(['update Lab Feed']);
  });

  it('still refuses a rename onto a name another channel holds', () => {
    const local = edited((c) => { channel(c, 'Lab  Feed')['name'] = 'lab feed'; });
    expect(() => planPush(local, config)).toThrow(/a name another channel holds/);
  });

  it('plans the deletes for a removed site channel', () => {
    const local = edited((c) => { (c['channels'] as Obj)['channel'] = channelsOf(c).filter((ch) => ch['name'] !== 'Site East 03'); });
    expect(planPush(local, config).changes.map((c) => `${c.op} ${c.label}`)).toEqual(['delete Site East 03']);
  });
});
